name: CI

on: 
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./Calculadora/
   
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
 
     - uses: actions/setup-python@v3
        
     - name: Install dependencies
       run: python -m pip install --upgrade pip
     - name: Build
       run: pip install build 
     - name: Flake8
       run: pip install flake8 pytest
   
     - run: pytest
